// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {youtube} from '../models';

export function DownloadVideo(arg1:string):Promise<void>;

export function GetVideoInfo(arg1:string):Promise<youtube.FormatList>;

export function Greet(arg1:string):Promise<string>;
