// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {youtube} from '../models';

export function CreateFolder(arg1:string):Promise<string>;

export function DownloadAudio(arg1:string,arg2:string):Promise<string>;

export function DownloadByQuality(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadVideo(arg1:string,arg2:string):Promise<string>;

export function GetPlaylist(arg1:string):Promise<youtube.Playlist>;
