// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DownloadAudio(arg1, arg2) {
  return window['go']['main']['App']['DownloadAudio'](arg1, arg2);
}

export function DownloadByQuality(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadByQuality'](arg1, arg2, arg3);
}

export function DownloadVideo(arg1, arg2) {
  return window['go']['main']['App']['DownloadVideo'](arg1, arg2);
}

export function GetPlaylist(arg1) {
  return window['go']['main']['App']['GetPlaylist'](arg1);
}
